SERVER = "__SERVER__"
CONNECT_INTERVAL = __CONNECT_INTERVAL__
IDLE_TIME = __IDLE_TIME__
MAX_FAILED_CONNECTIONS = __MAX_FAILED_CONNECTIONS__
PERSIST = __PERSIST__
SSL_VERIFY = __SSL_VERIFY__
HELP = ""
